build_student_data_docs <- function(output_base,
                                    dictionary_path = "docs/student_field_dictionary.csv") {
  db_path <- file.path(output_base, "tiktok_students.sqlite")
  if (!file.exists(db_path)) {
    stop("Student database not found at ", db_path)
  }

  dictionary_candidates <- unique(c(
    dictionary_path,
    file.path("docs", "student_field_dictionary.csv"),
    file.path(dirname(output_base), "docs", "student_field_dictionary.csv"),
    file.path(dirname(dirname(output_base)), "docs", "student_field_dictionary.csv"),
    file.path("tiktok-data", "docs", "student_field_dictionary.csv")
  ))
  dictionary_exists <- file.exists(dictionary_candidates)
  resolved_dictionary_path <- if (any(dictionary_exists)) dictionary_candidates[[which(dictionary_exists)[1]]] else NA_character_
  if (is.na(resolved_dictionary_path)) {
    warning(
      "Dictionary file not found. Attempted paths:\n",
      paste0("- ", dictionary_candidates, collapse = "\n"),
      "\nProceeding with placeholder field definitions."
    )
  }

  out_dir <- file.path(output_base, "documentation")
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

  con <- DBI::dbConnect(RSQLite::SQLite(), db_path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  objects <- DBI::dbGetQuery(
    con,
    "SELECT name, type FROM sqlite_master WHERE type IN ('table','view') AND name NOT LIKE 'sqlite_%' ORDER BY type, name"
  )

  objects <- tibble::as_tibble(objects) %>%
    dplyr::rename(object_name = name, object_type = type)

  table_rows <- purrr::map_dfr(objects$object_name[objects$object_type == "table"], function(obj) {
    n_rows <- DBI::dbGetQuery(con, paste0("SELECT COUNT(*) AS n FROM ", obj))$n[[1]]
    tibble::tibble(object_name = obj, row_count = as.numeric(n_rows))
  })

  view_rows <- tibble::tibble(
    object_name = objects$object_name[objects$object_type == "view"],
    row_count = NA_real_
  )

  object_catalog <- objects %>%
    dplyr::left_join(dplyr::bind_rows(table_rows, view_rows), by = "object_name")

  schema_inventory <- purrr::map_dfr(objects$object_name, function(obj) {
    DBI::dbGetQuery(con, paste0("PRAGMA table_info('", obj, "')")) %>%
      tibble::as_tibble() %>%
      dplyr::transmute(
        object_name = obj,
        column_name = name,
        sqlite_type = type,
        is_not_null = as.logical(notnull),
        is_primary_key = as.logical(pk)
      )
  })

  if (is.na(resolved_dictionary_path)) {
    dictionary <- tibble::tibble(
      object_name = character(0),
      column_name = character(0),
      business_definition = character(0),
      unit = character(0),
      student_use = character(0)
    )
  } else {
    dictionary <- readr::read_csv(resolved_dictionary_path, show_col_types = FALSE)
  }

  field_doc <- schema_inventory %>%
    dplyr::left_join(dictionary, by = c("object_name", "column_name")) %>%
    dplyr::mutate(
      business_definition = dplyr::coalesce(business_definition, "Definition pending"),
      unit = dplyr::coalesce(unit, "n/a"),
      student_use = dplyr::coalesce(student_use, "n/a")
    )

  readr::write_csv(object_catalog, file.path(out_dir, "student_object_catalog.csv"))
  readr::write_csv(field_doc, file.path(out_dir, "student_field_documentation.csv"))

  qmd_path <- file.path(out_dir, "student_database_documentation.qmd")
  qmd_lines <- c(
    "---",
    "title: \"Student Database Documentation\"",
    "format:",
    "  pdf:",
    "    toc: true",
    "    number-sections: true",
    "    fontsize: 11pt",
    "---",
    "",
    "## Scope",
    "",
    "This document describes the student-facing SQLite database generated by the TikTok teaching simulator.",
    "",
    "## Encoding Contract",
    "",
    "- Columns ending in `_at` are Unix timestamps in UTC (seconds).",
    "- Date fields are encoded as `YYYY-MM-DD` strings.",
    "- Views summarize raw logs and should not be treated as source logs.",
    "",
    "```{r}",
    "library(dplyr)",
    "library(readr)",
    "library(knitr)",
    "obj <- read_csv('student_object_catalog.csv', show_col_types = FALSE)",
    "fld <- read_csv('student_field_documentation.csv', show_col_types = FALSE)",
    "```",
    "",
    "## Object Catalog",
    "",
    "```{r}",
    "obj %>%",
    "  mutate(row_count = ifelse(is.na(row_count), NA, as.integer(row_count))) %>%",
    "  arrange(object_type, object_name) %>%",
    "  kable()",
    "```",
    "",
    "## Field Dictionary",
    "",
    "```{r}",
    "fld %>%",
    "  select(object_name, column_name, sqlite_type, business_definition, unit, student_use, is_not_null, is_primary_key) %>%",
    "  arrange(object_name, column_name) %>%",
    "  kable()",
    "```",
    "",
    "## Notes",
    "",
    "- `watch_logs` is the canonical event stream for student analyses.",
    "- `video_view` and `user_view` are convenience aggregate views.",
    "- Session boundaries and watch outcomes are intentionally derivable by students."
  )

  writeLines(qmd_lines, qmd_path)

  quarto_bin <- Sys.which("quarto")
  pdf_path <- file.path(out_dir, "student_database_documentation.pdf")
  html_path <- file.path(out_dir, "student_database_documentation.html")
  render_pdf <- character(0)
  render_html <- character(0)

  if (nchar(quarto_bin) == 0) {
    warning(
      "Quarto is not available on PATH. Skipping documentation rendering; ",
      "CSV documentation outputs are still available in ", out_dir
    )
  } else {
    render_pdf <- suppressWarnings(
      system2(
        quarto_bin,
        args = c("render", qmd_path, "--to", "pdf"),
        stdout = TRUE,
        stderr = TRUE
      )
    )

    if (!file.exists(pdf_path)) {
      warning(
        "Failed to render student database PDF. Trying HTML fallback. ",
        "If you need PDF output, install TinyTeX via tinytex::install_tinytex()."
      )
      render_html <- suppressWarnings(
        system2(
          quarto_bin,
          args = c("render", qmd_path, "--to", "html"),
          stdout = TRUE,
          stderr = TRUE
        )
      )
      if (!file.exists(html_path)) {
        warning(
          "HTML fallback render also failed. Quarto output (PDF attempt):\n",
          paste(render_pdf, collapse = "\n"),
          "\nQuarto output (HTML attempt):\n",
          paste(render_html, collapse = "\n")
        )
      }
    }
  }

  invisible(list(
    object_catalog = object_catalog,
    field_documentation = field_doc,
    pdf_path = if (file.exists(pdf_path)) pdf_path else NA_character_,
    html_path = if (file.exists(html_path)) html_path else NA_character_,
    dictionary_path = resolved_dictionary_path
  ))
}
