build_student_data_docs <- function(output_base,
                                    dictionary_path = "docs/student_field_dictionary.csv") {
  db_path <- file.path(output_base, "tiktok_students.sqlite")
  if (!file.exists(db_path)) {
    stop("Student database not found at ", db_path)
  }
  if (!file.exists(dictionary_path)) {
    stop("Dictionary file not found at ", dictionary_path)
  }

  out_dir <- file.path(output_base, "documentation")
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

  con <- DBI::dbConnect(RSQLite::SQLite(), db_path)
  on.exit(DBI::dbDisconnect(con), add = TRUE)

  objects <- DBI::dbGetQuery(
    con,
    "SELECT name, type FROM sqlite_master WHERE type IN ('table','view') AND name NOT LIKE 'sqlite_%' ORDER BY type, name"
  )

  objects <- tibble::as_tibble(objects) %>%
    dplyr::rename(object_name = name, object_type = type)

  table_rows <- purrr::map_dfr(objects$object_name[objects$object_type == "table"], function(obj) {
    n_rows <- DBI::dbGetQuery(con, paste0("SELECT COUNT(*) AS n FROM ", obj))$n[[1]]
    tibble::tibble(object_name = obj, row_count = as.numeric(n_rows))
  })

  view_rows <- tibble::tibble(
    object_name = objects$object_name[objects$object_type == "view"],
    row_count = NA_real_
  )

  object_catalog <- objects %>%
    dplyr::left_join(dplyr::bind_rows(table_rows, view_rows), by = "object_name")

  schema_inventory <- purrr::map_dfr(objects$object_name, function(obj) {
    DBI::dbGetQuery(con, paste0("PRAGMA table_info('", obj, "')")) %>%
      tibble::as_tibble() %>%
      dplyr::transmute(
        object_name = obj,
        column_name = name,
        sqlite_type = type,
        is_not_null = as.logical(notnull),
        is_primary_key = as.logical(pk)
      )
  })

  dictionary <- readr::read_csv(dictionary_path, show_col_types = FALSE)

  field_doc <- schema_inventory %>%
    dplyr::left_join(dictionary, by = c("object_name", "column_name")) %>%
    dplyr::mutate(
      business_definition = dplyr::coalesce(business_definition, "Definition pending"),
      unit = dplyr::coalesce(unit, "n/a"),
      student_use = dplyr::coalesce(student_use, "n/a")
    )

  readr::write_csv(object_catalog, file.path(out_dir, "student_object_catalog.csv"))
  readr::write_csv(field_doc, file.path(out_dir, "student_field_documentation.csv"))

  qmd_path <- file.path(out_dir, "student_database_documentation.qmd")
  qmd_lines <- c(
    "---",
    "title: \"Student Database Documentation\"",
    "format:",
    "  pdf:",
    "    toc: true",
    "    number-sections: true",
    "    fontsize: 11pt",
    "---",
    "",
    "## Scope",
    "",
    "This document describes the student-facing SQLite database generated by the TikTok teaching simulator.",
    "",
    "## Encoding Contract",
    "",
    "- Columns ending in `_at` are Unix timestamps in UTC (seconds).",
    "- Date fields are encoded as `YYYY-MM-DD` strings.",
    "- Views summarize raw logs and should not be treated as source logs.",
    "",
    "```{r}",
    "library(dplyr)",
    "library(readr)",
    "library(knitr)",
    "obj <- read_csv('student_object_catalog.csv', show_col_types = FALSE)",
    "fld <- read_csv('student_field_documentation.csv', show_col_types = FALSE)",
    "```",
    "",
    "## Object Catalog",
    "",
    "```{r}",
    "obj %>%",
    "  mutate(row_count = ifelse(is.na(row_count), NA, as.integer(row_count))) %>%",
    "  arrange(object_type, object_name) %>%",
    "  kable()",
    "```",
    "",
    "## Field Dictionary",
    "",
    "```{r}",
    "fld %>%",
    "  select(object_name, column_name, sqlite_type, business_definition, unit, student_use, is_not_null, is_primary_key) %>%",
    "  arrange(object_name, column_name) %>%",
    "  kable()",
    "```",
    "",
    "## Notes",
    "",
    "- `watch_logs` is the canonical event stream for student analyses.",
    "- `video_view` and `user_view` are convenience aggregate views.",
    "- Session boundaries and watch outcomes are intentionally derivable by students."
  )

  writeLines(qmd_lines, qmd_path)

  render_pdf <- suppressWarnings(
    system2(
      "quarto",
      args = c("render", qmd_path, "--to", "pdf"),
      stdout = TRUE,
      stderr = TRUE
    )
  )

  pdf_path <- file.path(out_dir, "student_database_documentation.pdf")
  if (!file.exists(pdf_path)) {
    msg <- paste(render_pdf, collapse = "\n")
    stop("Failed to render student database PDF. Quarto output:\n", msg)
  }

  invisible(list(
    object_catalog = object_catalog,
    field_documentation = field_doc,
    pdf_path = pdf_path
  ))
}
