window.CODE_QUEST.registerPack({
  id:'markdown', type:'markdown', title:'Week 2: Markdown Quest',
  description:'Practice Markdown by drafting a strong README with headings, emphasis, links, and useful sections.',
  setup:s=>{s.markdownDoc='# Project Title\n\n';},
  missions:[
    {mode:'reading',title:'Reading: Why Markdown matters',difficulty:'Prep',intro:'Before writing, connect Markdown to your week-2 workflow.',readingTitle:'Markdown is a general communication skill',readingBody:()=>`<p><strong>Markdown</strong> is lightweight formatting in plain text, so it works almost everywhere and stays version-control friendly.</p><p>You will use it in:</p><ul><li><strong>LLM output</strong> for structured answers and reports</li><li><strong>Quarto</strong> and <strong>R Markdown</strong> for analysis documents</li><li><strong>README files</strong> to explain what a project does and how to run it</li></ul><p>A good README helps teammates (and future you) understand setup, usage, and context quickly.</p>`,xp:40,unlock:()=>['markdown mindset']},
    {title:'Set the README title',difficulty:'Warm-up',intro:'A README should start with one clear project heading.',task:()=>`In the editor, add a <strong>level-1 heading</strong> at the top, for example <code># Spotify Trends Project</code>.`,hints:()=>['A level-1 heading starts with <code># </code>.','Use a project-specific name, not "My Project".'],solution:()=> '# Spotify Trends Project',check:s=>/^\s*#\s+.+/m.test(s.markdownDoc),xp:100,unlock:()=>['# heading']},
    {title:'Write a short overview',difficulty:'Rookie',intro:'Strong READMEs explain purpose in 1-2 lines.',task:()=>`Below the heading, add a short overview sentence that includes either <strong>italics</strong> or <strong>bold</strong>.`,hints:()=>['Use <code>*italics*</code> or <code>**bold**</code>.','Keep the overview concrete: what the project analyzes or produces.'],solution:()=> 'This project summarizes **streaming behavior** across markets.',check:s=>/\n\s*[^#\n].+/m.test(s.markdownDoc)&&(/\*\*[^*\n]+\*\*/.test(s.markdownDoc)||/\*[^*\n]+\*/.test(s.markdownDoc)||/_[^_\n]+_/.test(s.markdownDoc)),xp:110,unlock:()=>['overview writing']},
    {title:'Add Installation steps',difficulty:'Builder',intro:'Readers need reproducible setup instructions.',task:()=>`Add an <strong>Installation</strong> section (<code>## Installation</code>) with at least <strong>two numbered steps</strong>.`,hints:()=>['Use a level-2 heading: <code>## Installation</code>.','Numbered list example: <code>1. Clone repo</code>.'],solution:()=> '## Installation\n1. Clone the repository\n2. Open the project folder',check:s=>/##\s+Installation/i.test(s.markdownDoc)&&/(^|\n)\s*1\.\s+.+/m.test(s.markdownDoc)&&/(^|\n)\s*2\.\s+.+/m.test(s.markdownDoc),xp:120,unlock:()=>['installation section']},
    {title:'Add Usage guidance',difficulty:'Builder',intro:'Usage tells people how to run the work after setup.',task:()=>`Add a <strong>Usage</strong> section with at least <strong>two bullet points</strong> (for example how to run analysis or render Quarto).`,hints:()=>['Use <code>## Usage</code>.','Bullets can start with <code>- </code> or <code>* </code>.'],solution:()=> '## Usage\n- Run data preparation script\n- Render the Quarto report',check:s=>/##\s+Usage/i.test(s.markdownDoc)&&((s.markdownDoc.match(/(^|\n)\s*[-*]\s+.+/g)||[]).length>=2),xp:120,unlock:()=>['usage section']},
    {title:'Link key resources',difficulty:'Explorer',intro:'Links connect a README to data, docs, or deployed outputs.',task:()=>`Add at least one Markdown link, e.g. <code>[Quarto docs](https://quarto.org)</code>.`,hints:()=>['Pattern: <code>[label](https://url)</code>.'],solution:()=> '[Quarto docs](https://quarto.org)',check:s=>/\[[^\]\n]+\]\(https?:\/\/[^\)\s]+\)/.test(s.markdownDoc),xp:120,unlock:()=>['links']},
    {title:'README Boss',difficulty:'Boss fight',intro:'Final check: does your README include core best-practice sections?',task:()=>`Ensure your README now contains: <strong>title</strong>, <strong>Installation</strong>, <strong>Usage</strong>, and either <strong>Contributing</strong> or <strong>License</strong>.`,hints:()=>['Add missing sections with <code>## Section Name</code>.','Contributing can be one short sentence.'],solution:()=> '## Contributing\nContributions are welcome via pull requests.',check:s=>/^\s*#\s+.+/m.test(s.markdownDoc)&&/##\s+Installation/i.test(s.markdownDoc)&&/##\s+Usage/i.test(s.markdownDoc)&&(/##\s+Contributing/i.test(s.markdownDoc)||/##\s+License/i.test(s.markdownDoc)),xp:160,unlock:()=>['readme checklist']}
  ]
});
