window.CODE_QUEST.registerPack({
  id:'r-dplyr', type:'r', title:'Week 2: R Quest — dplyr',
  description:'Beginner dplyr practice with easy verbs and %>%. Keep the cheatsheet open while you work.',
  setup:(s,h)=>{s.env.products={type:'data.frame',rows:h.products()};},
  missions:[
    {mode:'reading',title:'Reading: dplyr verbs and cheatsheet',difficulty:'Prep',intro:'Before coding, keep the dplyr cheatsheet nearby.',readingTitle:'Use cheatsheets while learning',readingBody:()=>`<p><strong>dplyr</strong> has a few core verbs that you will reuse often.</p><p>In this beginner quest we focus on <code>select()</code>, <code>filter()</code>, <code>mutate()</code>, <code>group_by()</code>, and <code>summarize()</code>.</p><p>When you forget syntax, open the dplyr cheatsheet. That is normal professional workflow.</p>`,xp:40,unlock:()=>['dplyr cheatsheet habit']},
    {mode:'reading',title:'Reading: %>% pipeline thinking',difficulty:'Prep',intro:'Pipes make commands easier to read.',readingTitle:'Read left to right',readingBody:()=>`<p><code>%>%</code> means: take the table on the left and send it to the next function.</p><p>Example: <code>products %>% filter(category == "Food")</code>.</p>`,xp:40,unlock:()=>['%>% mindset']},
    {title:'Look at the table',difficulty:'Warm-up',intro:'First, inspect the data you will work with.',task:()=>`Run <strong>head(products)</strong>.`,hints:()=>['Type <code>head(products)</code>.'],solution:()=> 'head(products)',check:(s,r)=>r.action==='head',xp:90,unlock:()=>['head()']},
    {title:'Select one column',difficulty:'Warm-up',intro:'Start simple: keep only one column.',task:()=>`Run a pipe that keeps only the <strong>product</strong> column.`,hints:()=>['Start: <code>products %>%</code>.','Then: <code>select(product)</code>.'],solution:()=> 'products %>% select(product)',check:(s,r)=>r.value?.type==='data.frame'&&Object.keys(r.value.rows[0]||{}).join(',')==='product',xp:100,unlock:()=>['select()']},
    {title:'Filter one category',difficulty:'Warm-up',intro:'Now keep only food rows.',task:()=>`Filter rows where category is Food. You may type <code>"Food"</code>, <code>'Food'</code>, <code>"food"</code>, or <code>'food'</code>.`,hints:()=>['Try <code>products %>% filter(category == "food")</code>.'],solution:()=> 'products %>% filter(category == "food")',check:(s,r)=>r.value?.type==='data.frame'&&r.value.rows.length===3&&r.value.rows.every(x=>String(x.category).toLowerCase()==='food'),xp:100,unlock:()=>['filter()']},
    {title:'Create a new column',difficulty:'Rookie',intro:'mutate adds a calculated column.',task:()=>`Create object <strong>with_tax</strong> with <strong>price_eur = price * 1.2</strong>.`,hints:()=>['Use <code>with_tax <- products %>% mutate(price_eur = price * 1.2)</code>.'],solution:()=> 'with_tax <- products %>% mutate(price_eur = price * 1.2)',check:s=>s.env.with_tax?.type==='data.frame'&&Math.abs((s.env.with_tax.rows[0]?.price_eur||0)-4.8)<0.001,xp:110,unlock:()=>['mutate()']},
    {title:'Group and summarize',difficulty:'Boss fight',intro:'Final step: one mean per category.',task:()=>`Create <strong>by_cat</strong> with average sales per category using <strong>avg_sales = mean(sales)</strong>.`,hints:()=>['Use <code>group_by(category)</code> then <code>summarize(avg_sales = mean(sales))</code>.'],solution:()=> 'by_cat <- products %>% group_by(category) %>% summarize(avg_sales = mean(sales))',check:s=>{const t=s.env.by_cat; if(!t||t.type!=='data.frame'||t.rows.length!==2) return false; const drinks=t.rows.find(r=>r.category==='Drinks')?.avg_sales; const food=t.rows.find(r=>r.category==='Food')?.avg_sales; return Math.abs((drinks||0)-90)<0.001&&Math.abs((food||0)-110)<0.001;},xp:140,unlock:()=>['group_by()','summarize()']}
  ]
});
