window.CODE_QUEST.registerPack({
  id:'shell', type:'shell', title:'Week 1: Shell Quest',
  description:'Navigate folders, create directories, and clone a public repository on macOS or Windows.',
  missions:[
    {title:'Meet your terminal',difficulty:'Warm-up',intro:'The shell lets you interact with your computer by typing commands.',task:s=>`List the files and folders in your current directory using <strong>${s.os==='mac'?'ls':'dir'}</strong>.`,concept:'A directory is simply a folder. Your terminal always has a current working directory.',hints:s=>[`Use <code>${s.os==='mac'?'ls':'dir'}</code>.`,'Think: “list directory contents.”'],solution:s=>s.os==='mac'?'ls':'dir',check:(s,r)=>r.action==='list',unlock:s=>[s.os==='mac'?'ls':'dir'],xp:100},
    {mode:'reading',title:'Reading: Paths and folders',difficulty:'Prep',intro:'Before moving around, build a mental map of where commands run.',readingTitle:'How paths work',readingBody:s=>`<p>Your terminal always runs commands in one <strong>current directory</strong>.</p><p>Use <code>${s.os==='mac'?'ls':'dir'}</code> to inspect what is here now, then use <code>cd folder-name</code> to move into a child folder.</p><p><code>cd ..</code> means "go to the parent folder" (one level up).</p><ul><li>Think in a tree: home -> project -> subfolder.</li><li>Your prompt changes when your location changes.</li></ul>`,xp:40,unlock:()=>['path mental model']},
    {title:'Enter the quest folder',difficulty:'Explorer',intro:'Move one level down into a child folder.',task:()=>`Change directory into <strong>terminal-quest</strong>.`,concept:'cd means “change directory.”',hints:()=>['Use <code>cd</code> followed by the folder name.','Try <code>cd terminal-quest</code>.'],solution:()=> 'cd terminal-quest',check:s=>s.shellPath.join('/')==='terminal-quest',unlock:()=>['cd folder'],xp:100},
    {title:'Look around',difficulty:'Explorer',intro:'Inspect a directory after entering it.',task:s=>`List its contents with <strong>${s.os==='mac'?'ls':'dir'}</strong>.`,hints:s=>[`Use <code>${s.os==='mac'?'ls':'dir'}</code>.`],solution:s=>s.os==='mac'?'ls':'dir',check:(s,r)=>r.action==='list'&&s.shellPath.join('/')==='terminal-quest',xp:100},
    {title:'Go down one level',difficulty:'Navigator',intro:'The data folder is inside terminal-quest.',task:()=>`Enter the <strong>data</strong> folder.`,hints:()=>['Use <code>cd data</code>.'],solution:()=> 'cd data',check:s=>s.shellPath.join('/')==='terminal-quest/data',xp:100},
    {title:'Climb back up',difficulty:'Navigator',intro:'Two dots refer to the parent directory.',task:()=>`Move <strong>one folder up</strong>.`,hints:()=>['Combine <code>cd</code> with <code>..</code>.'],solution:()=> 'cd ..',check:s=>s.shellPath.join('/')==='terminal-quest',unlock:()=>['cd ..'],xp:100},
    {title:'Build a workspace',difficulty:'Builder',intro:'Create a dedicated folder for repositories.',task:()=>`Create a folder called <strong>repos</strong>.`,hints:()=>['Use <code>mkdir</code>.','Try <code>mkdir repos</code>.'],solution:()=> 'mkdir repos',check:s=>s.shellRepos,xp:100,unlock:()=>['mkdir']},
    {title:'Enter the repo zone',difficulty:'Builder',intro:'Move into the folder you just created.',task:()=>`Enter <strong>repos</strong>.`,hints:()=>['Use <code>cd repos</code>.'],solution:()=> 'cd repos',check:s=>s.shellPath.join('/')==='terminal-quest/repos',xp:100},
    {title:'Git Clone Boss',difficulty:'Boss fight',intro:'git clone downloads a repository and its history.',task:()=>`Clone <code>https://github.com/octocat/Hello-World.git</code>.`,hints:()=>['Structure: <code>git clone &lt;url&gt;</code>.'],solution:()=> 'git clone https://github.com/octocat/Hello-World.git',check:s=>s.shellCloned,xp:100,unlock:()=>['git clone']}
  ]
});
