---
title: "Exam preparation (week 6)"
subtitle: "Data Preparation and Programming Skills (2026/2027)"
author: "Hannes Datta"
date: "last-modified"
format: 
    beamer:
      theme: metropolis
      colortheme: seahorse
      linkcolor: blue


---

## Agenda

1. Exam setup
2. Example questions
3. Q&A & reflection

## Exam Setup

- 120-minute on-campus computer exam (course code 328059-M-6)
  - Mix of open and closed questions (e.g., multiple-choice, ranking (e.g., from low to high, high to low), matching items)
  - 120 points total (~1 point per minute)
- Closed-book exam
  - no internet access
  - selected cheat sheets will be available from the exam introduction page
  - no other resources or communication tools are allowed
- Do not include your name or student number in submitted files unless explicitly asked (anonymous grading)
- Four exam dates per academic year (maximum two attempts per academic year)

## Cognitive skills assessed on the exam

- Questions aligned with learning goals (tutorials + [dPrep book](https://dprep-book.hannesdatta.com))
- Bloom’s Taxonomy of Learning Objectives
  - Knowledge & Comprehension: Recall key concepts and demonstrate understanding
  - Application: Use techniques to solve new problems
  - Analysis: Break down and solve complex tasks (e.g., using datasets, workflows)
  - Evaluation: Critically judge suitability of approaches or compare solutions
  - Synthesis: Combine elements (data, code, interpretation) into coherent results

## Overview of Questions

| LG | Learning goal | Tutorials/project | Book |
|----|---------------|-------------------|------|
| 1 | GitHub for empirical project management | — | 10P (3Q), ch. 2, 5 |
| 2 | Git/GitHub versioning and collaboration | 24P (1Q) | 10P (3Q), ch. 6 |
| 3 | R and SQL for data cleaning and transformation | 20P (2Q) | 4P (1Q), ch. 7 |
| 4 | R for automated reports | 12P | 6P (2Q), ch. 4 |
| 5 | Workflow-management tools | 18P | 6P (2Q), ch. 3, 8 |
| 6 | LLMs and software agents | 6P (1Q) | 4P (2Q), ch. 9 |

# Preparing for the Exam

## Technical Tips

- **Be familiar with your exam environment**:
  - Practice using **Windows**, RStudio, and the command prompt.
- **Know how to manage files and directories**:
  - Store data locally (not on a network drive) and organize files by question (e.g., in `C:\Users\<YOUR-U-NUMBER>\Downloads`).
  - Know how to load `.RData` files (`load('downloaded_data.RData')`).
  - Zip entire Git repositories before uploading.

## Technical Tips (continued)

- **Make sure to know the basics of code management**:
  - Set working directories in RStudio via `Session → Set Working Directory → To Source File Location`.
  - Revise code so it runs cleanly from top to bottom.
  - Do not include your name or student number in files, folders, or code.
- **Prepare for offline work**:
  - Practice installing packages locally; internet access will not be available during the exam.
  - Open required software and set working directories before the exam begins.

## Familiarize yourself with TestVision

- Know how to work with [TestVision](https://www.tilburguniversity.edu/students/studying/exams/e-assessment/testvision)
  - learn how to upload & download files
  - understand how to unzip repositories, and rezip them for file submission
  - see how to fill in answers into text boxes and view the word count
  - get a general understanding of how TestVision works
  
::: callout
- Please take the **technical practice exam**; a link will be shared on Canvas.
- Please explore [TestVision’s generic practice exam](https://oefentoetsen.testvision.nl/online/fe/login_ot.htm?campagne=tlb_demo_eng&taal=2).
:::

## Cheatsheets

- **Official cheatsheets** for R, make, and Git will be provided during the exam (view [previous year's cheatsheets](https://github.
com/hannesdatta/course-dprep/raw/main/material/exam/cheatsheets/cheatsheets-exam.
zip))
- **One collective cheatsheet**
  - Drafted collaboratively in Google Docs, reviewed by the instructor, and shared as PDF.
  - [Link to the document](https://docs.google.com/document/d/1nLEkypEmP3dTkljidmAiGmHptm0Bfe44LnwaYUnkdnU/edit?usp=sharing)
  - Deadline to make your changes: 8 October 2026.
  - Page limit: 50 pages.
  - I will review the document, make changes where required, and add it to the cheatsheets.

## TestVision’s Introduction Page

- Every exam begins with an **introduction/cover page** containing official instructions.
- I will show you example cover pages now (see also PDF)
- Please review in advance: The cover page will be available on Canvas before the exam

## Questions so far?

# Example Questions

## Example Questions 

see PDF file posted on Canvas

## Ideas for Developing Your Proficiency

- Work through the example questions and tutorials.
- Download data and create own "engineering" questions using common data operations from tutorial #3.
- Share (public) links to your teams’ GitHub repositories & fork and clone them.
  - `make`: run workflows with `make` (using the README); does it run? if not, can you fix the `makefile`?
  - Git/GitHub: work on someone else’s project (new feature branch, improve code, commit to your fork, and make a PR); *receiving teams*: review contributions and integrate PRs.

Above all, see this exam preparation *not* just as exam study, but as a way to strengthen and share your skills.

## Remaining questions?

## Next steps

- Reflection on tutorials
- Course evaluation
- Closing lecture next week
- Final coaching session (Roshini)

<br>
Thanks!
