---
title: "Week 1) Start coding in R, use the terminal, and make your first Git commit"
format: html
---

<!--__Obtain business and data understanding, and explore data in R__-->

__Learning Goals__

- Coding: use base R and the Setup-Input-Transform-Output (ITO) logic for simple data tasks.
- Collaboration: use `git status`, `git add`, and `git commit` to create your first clear version history.
- Automation: run scripts from the command line using terminal/command prompt and `Rscript`.

__Preparation before class__

- Please complete the software installation (see &rarr; Preparation before the course starts)
- Please read [chapters 1-2 of "Marketing Analytics: A Modern Toolkit"](https://dprep-book.hannesdatta.com/) (and optionally the Appendix: R - A Gentle Introduction)
- Please complete the [code quests](https://code-quest.hannesdatta.com) for week 1 (Shell Quest and R Quest - Basics)

__Opening lecture and R bootcamp__

- Introduction to the course <!--(View [slides](slides.html))-->
- In-class tutorial: R Bootcamp <!-- ([view slides](tutorial-inclass.html), view [full tutorial (chapters 1-4)](https://datacarpentry.org/r-socialsci/))-->

__After the lecture__

- Complete all exercises from the tutorial shared with students this week.

__Optional practice__

- Work through [R for Social Scientists](https://datacarpentry.org/r-socialsci/) chapters 1-4.


<!--- Reading: [A Guide to Scrum for Researchers](https://tilburgsciencehub.com/learn/scrum)
-->
<!--
- Readings
  - [Data Selection and Procurement](https://doi.org/10.1287/mksc.1110.0650) [^1]
-->

<!--
- [Data exploration with R and RMarkdown (Tutorial and Data Challenge 1)](docs/tutorials/data-exploration-in-r)
- [Data Selection and Procurement](https://doi.org/10.1287/mksc.1110.0650) [^1]
<!--- Demo clips on efficiency gains <!-- (2-minute clips); or podcasts-->

[^1]: Mela, C. F. (2011). Structural Workshop Paper—Data Selection and Procurement. *Marketing Science*, 30(6), 965-976. [https://doi.org/10.1287/mksc.1110.0650](https://doi.org/10.1287/mksc.1110.0650)

<!--
- [Activity to explore new data](activity.md)
- Q&A on Data Challenge #1

[^1]: Mela, C. F. (2011). Structural Workshop Paper—Data Selection and Procurement. *Marketing Science*, 30(6), 965-976. [https://doi.org/10.1287/mksc.1110.0650](https://doi.org/10.1287/mksc.1110.0650)

<!--

Meetup
- Introduction to the course *live*
  - Course objectives and practical arrangements
  - Workflow overview
  - Relevance of workflow management
-->
<!--  - Any remaining questions, please post them by DEADLINE on XXXX-->

<!--
- Reading: Web scraping workflow

- Self-study
  - Readings
    - Web scraping article Hannes/Johannes/Abhi/Andrew
    - Ethics in scraping and APIs

  - Video: Assessing research fit of web scraping and APIs [recorded]


- Self study
  - sdasd
    - data enrichment (e.g., ML APIs)
    - data collection and intelligence (e.g., search; chartmetric)
    - market research (e.g., pricewatch)

-->
