---
title: "Week 3) Project Management and Version Control"
format: html
---

<!--__Obtain business and data understanding, and explore data in R__-->

__Learning Goals__

- Understand and apply basic Git commands and workflows for version control in software projects.
- Set up and manage repositories on GitHub, including creating branches, committing changes, and resolving conflicts.
- Collaborate effectively on projects using GitHub, including using pull requests and branching strategies.
- Gain proficiency in restoring previous versions of work and managing repository contents using `.gitignore` and other Git features.


__Preparation before class__

- Improve your knowledge about [Shell/Bash in this Datacamp tutorial](https://www.datacamp.com/courses/introduction-to-shell) (first chapter only, "manipulating files and directories")
- Please read [chapter 4](https://dprep-book.hannesdatta.com/) of "Marketing Analytics: A Modern Toolkit"

__Tutorial__

- Tutorial <!-- (view [slides](tutorial/tutorial-inclass.html), view [complete tutorial](tutorial/version-control.html))
-->

__Coaching session__

- Work on your team goals for this course week (see coaching #2 on your workplan)

__After the lecture__

- Complete all exercises in this week's tutorial <!--([View tutorial](tutorial/version-control.html))-->
<!--- [Reading: Principles of Project Setup and Workflow Management](https://tilburgsciencehub.com/learn/project-setup) (30 minutes)
-->

__Tips & tricks__

- Curious how to use Git with a graphical user interface?
  - Use Git directly from within R - [find out how!](https://swcarpentry.github.io/git-novice/14-supplemental-rstudio/)
  - Another fantastic Git client is [Sourcetreeapp](https://www.sourcetreeapp.com), which works on Windows, Mac and Linux!
- [Git & Github cheatsheet](https://tilburgsciencehub.com/topics/automation/version-control/start-git/images/github_cheatsheet_tsh.pdf)

<!-- 
-- Optional activity: [Contributing to an open source web site](activity)
-->

<!--
- Readings
  - [Data Selection and Procurement](https://doi.org/10.1287/mksc.1110.0650) [^1]
-->

<!--
- [Data exploration with R and RMarkdown (Tutorial and Data Challenge 1)](docs/tutorials/data-exploration-in-r)
- [Data Selection and Procurement](https://doi.org/10.1287/mksc.1110.0650) [^1]
<!--- Demo clips on efficiency gains <!-- (2-minute clips); or podcasts-->

[^1]: Mela, C. F. (2011). Structural Workshop Paper—Data Selection and Procurement. *Marketing Science*, 30(6), 965-976. [https://doi.org/10.1287/mksc.1110.0650](https://doi.org/10.1287/mksc.1110.0650)

<!--
- [Activity to explore new data](activity.md)
- Q&A on Data Challenge #1

[^1]: Mela, C. F. (2011). Structural Workshop Paper—Data Selection and Procurement. *Marketing Science*, 30(6), 965-976. [https://doi.org/10.1287/mksc.1110.0650](https://doi.org/10.1287/mksc.1110.0650)

<!--

Meetup
- Introduction to the course *live*
  - Course objectives and practical arrangements
  - Workflow overview
  - Relevance of workflow management
-->
<!--  - Any remaining questions, please post them by DEADLINE on XXXX-->

<!--
- Reading: Web scraping workflow

- Self-study
  - Readings
    - Web scraping article Hannes/Johannes/Abhi/Andrew
    - Ethics in scraping and APIs

  - Video: Assessing research fit of web scraping and APIs [recorded]


- Self study
  - sdasd
    - data enrichment (e.g., ML APIs)
    - data collection and intelligence (e.g., search; chartmetric)
    - market research (e.g., pricewatch)

-->

